// ─────────────────────────────────────────────────────────────────────────────
// FoodDB.js — v1.9.1
//
// Database alimenti e derivazione ALL_FOODS, estratti da useNutriFox.js dove
// erano già isolati e pronti per questo passaggio fin dalla v1.4.1. Nessun
// dato cambiato, solo spostato: questo file non contiene alcuna logica,
// solo dati e la derivazione piatta usata per ricerca/filtri.
//
// v1.9: +10 alimenti (249 totali) mirati a completare i pool usati dal nuovo
// Meal Builder intelligente — contorni/verdure, cereali "carb", proteine
// magre pronte e opzioni bilanciate per colazione/spuntino.
//
// v1.9.1: +3 alimenti (252 totali) — salmone al forno e ceci in insalata
// (altre proteine per il Meal Builder), tè verde.
// ─────────────────────────────────────────────────────────────────────────────
 
export const FOOD_DB = {
  "Carne e Pesce": [
    { name:"Petto di pollo",            kcal:165, p:31, c:0,  f:3.6, type:"protein" },
    { name:"Coscia di pollo",           kcal:215, p:26, c:0,  f:12,  type:"protein" },
    { name:"Pollo arrosto",             kcal:239, p:27, c:0,  f:14,  type:"protein" },
    { name:"Bistecca di manzo",         kcal:250, p:26, c:0,  f:16,  type:"protein" },
    { name:"Macinato di manzo",         kcal:280, p:25, c:0,  f:20,  type:"protein" },
    { name:"Lonza di maiale",           kcal:185, p:29, c:0,  f:7,   type:"protein" },
    { name:"Fesa di tacchino",          kcal:135, p:29, c:0,  f:1.5, type:"protein" },
    { name:"Agnello (coscia)",          kcal:258, p:25, c:0,  f:17,  type:"protein" },
    { name:"Salmone al forno",          kcal:208, p:28, c:0,  f:10,  type:"protein" },
    { name:"Tonno in scatola",          kcal:130, p:28, c:0,  f:1.5, type:"protein" },
    { name:"Merluzzo",                  kcal:82,  p:18, c:0,  f:0.7, type:"protein" },
    { name:"Orata al forno",            kcal:120, p:22, c:0,  f:3.5, type:"protein" },
    { name:"Branzino al forno",         kcal:115, p:21, c:0,  f:3.2, type:"protein" },
    { name:"Sgombro in scatola",        kcal:200, p:19, c:0,  f:14,  type:"protein" },
    { name:"Alici sott'olio (50g)",     kcal:95,  p:13, c:0,  f:5,   type:"protein" },
    { name:"Polpo lessato",             kcal:82,  p:15, c:2,  f:1,   type:"protein" },
    { name:"Seppie",                    kcal:79,  p:16, c:0.8,f:1,   type:"protein" },
    { name:"Gamberetti",                kcal:99,  p:20, c:0.9,f:1.7, type:"protein" },
    { name:"Cozze (100g)",              kcal:86,  p:12, c:3.7,f:2.2, type:"protein" },
    { name:"Prosciutto cotto",          kcal:130, p:19, c:1,  f:5.5, type:"protein" },
    { name:"Prosciutto di Parma",       kcal:90,  p:7,  c:0,  f:7,   type:"protein" },
    { name:"Culatello",                 kcal:95,  p:8,  c:0,  f:7,   type:"protein" },
    { name:"Bresaola",                  kcal:98,  p:21, c:0,  f:1.5, type:"protein" },
    { name:"Mortadella Bologna",        kcal:155, p:7.5,c:0.5,f:14,  type:"fat"     },
    { name:"Salsiccia",                 kcal:302, p:13, c:2,  f:27,  type:"fat"     },
    { name:"Cotechino (porzione)",      kcal:320, p:14, c:1,  f:29,  type:"fat"     },
    { name:"Cotoletta alla bolognese",  kcal:380, p:28, c:12, f:24,  type:"protein" },
    { name:"Spezzatino di manzo",       kcal:210, p:24, c:4,  f:10,  type:"protein" },
    { name:"Polpette al sugo (3)",      kcal:280, p:18, c:12, f:17,  type:"protein" },
    { name:"Pollo alla cacciatora",     kcal:260, p:28, c:6,  f:14,  type:"protein" },
    { name:"Tonno alla griglia",        kcal:200, p:34, c:0,  f:7,   type:"protein" },
    { name:"Petto di tacchino grigliato", kcal:150, p:32, c:0, f:1.8, type:"protein" },
    { name:"Ceviche di pesce (100g)",   kcal:110, p:18, c:4,  f:2,   type:"protein" },
    { name:"Involtini di pollo (2 pz)", kcal:220, p:26, c:4,  f:11,  type:"protein" },
    { name:"Filetto di merluzzo al vapore", kcal:90, p:19, c:0, f:1, type:"protein" },
    { name:"Straccetti di manzo (100g)", kcal:190, p:27, c:0, f:9, type:"protein" },
    { name:"Hamburger di manzo al naturale (100g)", kcal:215, p:26, c:0, f:12, type:"protein" },
    { name:"Petto di pollo alla piastra (100g)", kcal:160, p:31, c:0, f:3.2, type:"protein" },
    { name:"Bocconcini di tacchino saltati (100g)", kcal:145, p:30, c:0, f:2, type:"protein" },
    { name:"Salmone al forno (100g)",   kcal:206, p:22, c:0, f:13,  type:"protein" },
  ],
  "Uova e Latticini": [
    { name:"Uovo intero",               kcal:78,  p:6,  c:0.6,f:5,   type:"protein" },
    { name:"Uova strapazzate (2)",      kcal:180, p:14, c:1,  f:13,  type:"protein" },
    { name:"Frittata (2 uova)",         kcal:210, p:14, c:2,  f:16,  type:"protein" },
    { name:"Uova sode (2)",             kcal:156, p:12, c:1,  f:11,  type:"protein" },
    { name:"Mozzarella",                kcal:280, p:18, c:2,  f:22,  type:"fat"     },
    { name:"Parmigiano Reggiano",       kcal:119, p:10, c:0,  f:8.5, type:"protein" },
    { name:"Grana Padano",              kcal:114, p:10, c:0,  f:8,   type:"protein" },
    { name:"Pecorino (30g)",            kcal:120, p:8,  c:0.5,f:10,  type:"fat"     },
    { name:"Ricotta",                   kcal:174, p:11, c:3,  f:13,  type:"fat"     },
    { name:"Squacquerone (50g)",        kcal:130, p:6,  c:1,  f:11,  type:"fat"     },
    { name:"Stracchino (50g)",          kcal:120, p:7,  c:0.5,f:10,  type:"fat"     },
    { name:"Yogurt greco",              kcal:100, p:10, c:6,  f:3,   type:"protein" },
    { name:"Yogurt bianco",             kcal:61,  p:3.5,c:7,  f:1.5, type:"light"   },
    { name:"Kefir (200ml)",             kcal:90,  p:6,  c:9,  f:2.5, type:"protein" },
    { name:"Latte intero (200ml)",      kcal:130, p:6.6,c:9.6,f:7.4, type:"fat"     },
    { name:"Latte scremato (200ml)",    kcal:70,  p:6.8,c:9.8,f:0.2, type:"light"   },
    { name:"Burrata",                   kcal:330, p:15, c:2,  f:30,  type:"fat"     },
  ],
  "Pasta e Cereali": [
    { name:"Pasta al pomodoro",         kcal:350, p:12, c:65, f:5,   type:"carb"    },
    { name:"Pasta in bianco",           kcal:290, p:10, c:58, f:3,   type:"carb"    },
    { name:"Pasta al pesto",            kcal:420, p:12, c:60, f:16,  type:"carb"    },
    { name:"Pasta alla norma",          kcal:380, p:10, c:62, f:11,  type:"carb"    },
    { name:"Pasta al ragu",             kcal:450, p:20, c:58, f:15,  type:"carb"    },
    { name:"Pasta e fagioli",           kcal:280, p:14, c:45, f:5,   type:"carb"    },
    { name:"Pasta e ceci",              kcal:290, p:13, c:48, f:4,   type:"carb"    },
    { name:"Tagliatelle al ragu",       kcal:480, p:22, c:52, f:18,  type:"carb"    },
    { name:"Tortellini in brodo",       kcal:320, p:14, c:42, f:10,  type:"carb"    },
    { name:"Tortellini panna e prosciutto", kcal:520, p:18, c:48, f:26, type:"fat"  },
    { name:"Lasagne verdi bolognese",   kcal:420, p:20, c:38, f:20,  type:"carb"    },
    { name:"Spaghetti alle vongole",    kcal:380, p:18, c:58, f:9,   type:"carb"    },
    { name:"Riso bollito",              kcal:130, p:2.7,c:28, f:0.3, type:"carb"    },
    { name:"Riso integrale",            kcal:150, p:3.5,c:30, f:1.5, type:"carb"    },
    { name:"Risotto ai funghi",         kcal:320, p:8,  c:52, f:9,   type:"carb"    },
    { name:"Risotto allo zafferano",    kcal:340, p:8,  c:55, f:10,  type:"carb"    },
    { name:"Risotto ai gamberetti",     kcal:360, p:16, c:52, f:9,   type:"carb"    },
    { name:"Gnocchi al pomodoro",       kcal:310, p:8,  c:58, f:5,   type:"carb"    },
    { name:"Pane bianco",               kcal:134, p:4,  c:27, f:0.9, type:"carb"    },
    { name:"Pane integrale",            kcal:120, p:5,  c:22, f:1.5, type:"carb"    },
    { name:"Pane di segale",            kcal:110, p:4.5,c:20, f:1,   type:"carb"    },
    { name:"Focaccia (100g)",           kcal:280, p:7,  c:40, f:9,   type:"carb"    },
    { name:"Piadina romagnola",         kcal:290, p:7,  c:42, f:10,  type:"carb"    },
    { name:"Gnocco fritto",             kcal:340, p:6,  c:38, f:18,  type:"fat"     },
    { name:"Tigella",                   kcal:220, p:6,  c:32, f:8,   type:"carb"    },
    { name:"Polenta (100g)",            kcal:83,  p:2,  c:18, f:0.5, type:"carb"    },
    { name:"Farro (100g cotto)",        kcal:150, p:6,  c:30, f:1,   type:"carb"    },
    { name:"Orzo (100g cotto)",         kcal:123, p:3,  c:25, f:0.4, type:"carb"    },
    { name:"Quinoa (100g cotta)",       kcal:120, p:4.4,c:22, f:1.9, type:"carb"    },
    { name:"Avena (porridge 200ml)",    kcal:150, p:5,  c:27, f:3,   type:"carb"    },
    { name:"Crackers (5 pz)",           kcal:110, p:2.5,c:18, f:3.5, type:"carb"    },
    { name:"Pasta alla carbonara",      kcal:460, p:18, c:55, f:18,  type:"carb"    },
    { name:"Pasta integrale al pomodoro", kcal:310, p:12, c:56, f:3, type:"carb"    },
    { name:"Riso basmati (100g cotto)", kcal:135, p:2.9,c:29, f:0.3, type:"carb"    },
    { name:"Cous cous (100g cotto)",    kcal:112, p:3.8,c:23, f:0.2, type:"carb"    },
  ],
  "Verdure e Legumi": [
    { name:"Insalata mista",            kcal:15,  p:1,  c:2,  f:0.2, type:"light"   },
    { name:"Pomodori (100g)",           kcal:18,  p:0.9,c:3.5,f:0.2, type:"light"   },
    { name:"Zucchine",                  kcal:17,  p:1.2,c:3.1,f:0.3, type:"light"   },
    { name:"Melanzane",                 kcal:25,  p:1,  c:6,  f:0.2, type:"light"   },
    { name:"Peperoni",                  kcal:31,  p:1,  c:6,  f:0.3, type:"light"   },
    { name:"Spinaci",                   kcal:23,  p:2.9,c:3.6,f:0.4, type:"light"   },
    { name:"Broccoli",                  kcal:34,  p:2.8,c:7,  f:0.4, type:"light"   },
    { name:"Cavolfiore",                kcal:25,  p:1.9,c:5,  f:0.3, type:"light"   },
    { name:"Carote (100g)",             kcal:41,  p:0.9,c:10, f:0.2, type:"light"   },
    { name:"Asparagi (100g)",           kcal:20,  p:2.2,c:3.7,f:0.2, type:"light"   },
    { name:"Carciofi (100g)",           kcal:47,  p:3.3,c:10, f:0.2, type:"light"   },
    { name:"Fagiolini (100g)",          kcal:31,  p:1.8,c:7,  f:0.2, type:"light"   },
    { name:"Funghi champignon",         kcal:22,  p:3,  c:4,  f:0.3, type:"light"   },
    { name:"Funghi porcini",            kcal:28,  p:3.7,c:4.3,f:0.5, type:"light"   },
    { name:"Rucola (50g)",              kcal:20,  p:2.5,c:2,  f:0.7, type:"light"   },
    { name:"Rape rosse cotte",          kcal:43,  p:1.6,c:10, f:0.2, type:"light"   },
    { name:"Cavolo cappuccio (100g)",   kcal:25,  p:1.3,c:6,  f:0.1, type:"light"   },
    { name:"Ceci cotti",                kcal:164, p:8.9,c:27, f:2.6, type:"carb"    },
    { name:"Lenticchie cotte",          kcal:116, p:9,  c:20, f:0.4, type:"protein" },
    { name:"Fagioli borlotti (100g)",   kcal:128, p:8.7,c:21, f:0.5, type:"protein" },
    { name:"Fagioli cannellini (100g)", kcal:120, p:9,  c:20, f:0.5, type:"protein" },
    { name:"Piselli (100g)",            kcal:81,  p:5,  c:14, f:0.4, type:"carb"    },
    { name:"Edamame (100g)",            kcal:122, p:11, c:10, f:5,   type:"protein" },
    { name:"Patate lesse (100g)",       kcal:77,  p:2,  c:17, f:0.1, type:"carb"    },
    { name:"Patate al forno",           kcal:150, p:3,  c:30, f:3,   type:"carb"    },
    { name:"Minestrone",                kcal:85,  p:4,  c:14, f:1.5, type:"light"   },
    { name:"Passata di pomodoro (100g)",kcal:24,  p:1.1,c:5,  f:0.2, type:"light"   },
    { name:"Erbazzone",                 kcal:220, p:8,  c:22, f:11,  type:"fat"     },
    { name:"Zuppa di lenticchie",       kcal:140, p:9,  c:22, f:2,   type:"protein" },
    { name:"Caponata (100g)",           kcal:90,  p:1.5,c:9,  f:5,   type:"light"   },
    { name:"Melanzane a funghetto",     kcal:90,  p:2,  c:8,  f:6,   type:"light"   },
    { name:"Zucca al forno (150g)",     kcal:65,  p:1.5,c:14, f:0.3, type:"light"   },
    { name:"Hummus di ceci fatto in casa (50g)", kcal:120, p:4.5,c:9,  f:8,  type:"protein" },
    { name:"Insalata di finocchi e arance (150g)", kcal:60, p:1.5,c:13, f:0.3, type:"light" },
    { name:"Verdure grigliate miste (150g)", kcal:70,  p:2,  c:9,  f:2.5, type:"light" },
    { name:"Puré di patate (100g)",      kcal:105, p:2,  c:16, f:3.5, type:"carb"    },
    { name:"Ceci in insalata (100g)",    kcal:120, p:7,  c:18, f:2,   type:"protein" },
  ],
  "Frutta": [
    { name:"Mela",                      kcal:72,  p:0.4,c:19, f:0.2, type:"light"   },
    { name:"Banana",                    kcal:105, p:1.3,c:27, f:0.4, type:"carb"    },
    { name:"Arancia",                   kcal:62,  p:1.2,c:15, f:0.2, type:"light"   },
    { name:"Mandarino (2 pz)",          kcal:70,  p:1,  c:17, f:0.3, type:"light"   },
    { name:"Pera",                      kcal:57,  p:0.4,c:15, f:0.1, type:"light"   },
    { name:"Pesca",                     kcal:39,  p:0.9,c:10, f:0.3, type:"light"   },
    { name:"Albicocche (2 pz)",         kcal:48,  p:1.4,c:11, f:0.4, type:"light"   },
    { name:"Fragole (100g)",            kcal:32,  p:0.7,c:8,  f:0.3, type:"light"   },
    { name:"Ciliegie (100g)",           kcal:63,  p:1,  c:16, f:0.2, type:"light"   },
    { name:"Uva (100g)",                kcal:69,  p:0.7,c:18, f:0.2, type:"light"   },
    { name:"Kiwi",                      kcal:61,  p:1.1,c:15, f:0.5, type:"light"   },
    { name:"Mango (100g)",              kcal:60,  p:0.8,c:15, f:0.4, type:"light"   },
    { name:"Ananas (100g)",             kcal:50,  p:0.5,c:13, f:0.1, type:"light"   },
    { name:"Anguria (200g)",            kcal:60,  p:1.2,c:15, f:0.2, type:"light"   },
    { name:"Melone (200g)",             kcal:68,  p:1.7,c:16, f:0.3, type:"light"   },
    { name:"Lamponi (100g)",            kcal:52,  p:1.2,c:12, f:0.7, type:"light"   },
    { name:"Mirtilli (100g)",           kcal:57,  p:0.7,c:14, f:0.3, type:"light"   },
    { name:"Avocado",                   kcal:160, p:2,  c:9,  f:15,  type:"fat"     },
    { name:"Frutto della passione (2)", kcal:48,  p:2,  c:11, f:0.4, type:"light"   },
    { name:"Fico (2 pz)",               kcal:74,  p:0.8,c:19, f:0.3, type:"light"   },
    { name:"Cocco (30g)",               kcal:106, p:1,  c:4,  f:10,  type:"fat"     },
  ],
  "Sughi e Condimenti": [
    { name:"Sugo al pomodoro (100g)",   kcal:45,  p:1.5,c:8,  f:1.2, type:"light"   },
    { name:"Sugo all'arrabbiata",       kcal:55,  p:1.5,c:8,  f:2.5, type:"light"   },
    { name:"Ragu bolognese (100g)",     kcal:150, p:10, c:6,  f:10,  type:"protein" },
    { name:"Pesto alla genovese (30g)", kcal:130, p:2.5,c:1.5,f:13,  type:"fat"     },
    { name:"Besciamella (50ml)",        kcal:72,  p:2,  c:5,  f:5,   type:"fat"     },
    { name:"Olio d'oliva (10ml)",       kcal:90,  p:0,  c:0,  f:10,  type:"fat"     },
    { name:"Burro (10g)",               kcal:74,  p:0.1,c:0,  f:8.3, type:"fat"     },
    { name:"Aceto balsamico (15ml)",    kcal:21,  p:0.2,c:5,  f:0,   type:"light"   },
    { name:"Maionese (15g)",            kcal:104, p:0.2,c:0.3,f:11,  type:"fat"     },
    { name:"Salsa di soia (15ml)",      kcal:9,   p:1.3,c:0.9,f:0,   type:"light"   },
    { name:"Hummus (50g)",              kcal:115, p:4,  c:9,  f:7,   type:"protein" },
    { name:"Guacamole (50g)",           kcal:80,  p:1,  c:4,  f:7,   type:"fat"     },
    { name:"Tzatziki (50g)",            kcal:55,  p:3,  c:3,  f:3,   type:"light"   },
    { name:"Salsa BBQ (30g)",           kcal:60,  p:0.3,c:14, f:0.2, type:"carb"    },
  ],
  "Surgelati": [
    { name:"Bastoncini di pesce (2)",   kcal:160, p:8,  c:16, f:7,   type:"carb"    },
    { name:"Sofficini (2)",             kcal:280, p:8,  c:30, f:14,  type:"carb"    },
    { name:"Lasagne surgelate",         kcal:380, p:18, c:38, f:16,  type:"carb"    },
    { name:"Cannelloni surgelati",      kcal:290, p:14, c:28, f:13,  type:"carb"    },
    { name:"Pizza surgelata (meta)",    kcal:420, p:14, c:54, f:16,  type:"carb"    },
    { name:"Crocchette pollo (3)",      kcal:220, p:12, c:18, f:11,  type:"protein" },
    { name:"Cotolette di pesce",        kcal:180, p:10, c:14, f:9,   type:"protein" },
    { name:"Cordon bleu (1 pz)",        kcal:280, p:16, c:16, f:16,  type:"protein" },
    { name:"Minestrone surgelato",      kcal:60,  p:3,  c:11, f:0.5, type:"light"   },
    { name:"Spinaci surgelati",         kcal:22,  p:2.8,c:2,  f:0.4, type:"light"   },
    { name:"Verdure miste surgelate",   kcal:45,  p:3,  c:8,  f:0.5, type:"light"   },
    { name:"Patatine fritte surgelate", kcal:270, p:3.5,c:36, f:13,  type:"carb"    },
    { name:"Wurstel",                   kcal:120, p:5,  c:1,  f:11,  type:"fat"     },
    { name:"Tortellini surgelati",      kcal:340, p:15, c:44, f:11,  type:"carb"    },
    { name:"Burger di soia surgelato",  kcal:180, p:16, c:14, f:6,   type:"protein" },
    { name:"Edamame surgelato (100g)",  kcal:122, p:11, c:10, f:5,   type:"protein" },
  ],
  "Piatti pronti": [
    { name:"Pizza margherita (fetta)",  kcal:270, p:11, c:35, f:9,   type:"carb"    },
    { name:"Pizza 4 stagioni (fetta)",  kcal:290, p:13, c:33, f:11,  type:"carb"    },
    { name:"Pizza bianca (100g)",       kcal:310, p:9,  c:48, f:9,   type:"carb"    },
    { name:"Hamburger classico",        kcal:480, p:26, c:40, f:24,  type:"fat"     },
    { name:"Piadina squacquerone",      kcal:480, p:14, c:52, f:24,  type:"fat"     },
    { name:"Piadina prosciutto rucola", kcal:440, p:18, c:46, f:20,  type:"carb"    },
    { name:"Tramezzino tonno",          kcal:350, p:14, c:42, f:13,  type:"carb"    },
    { name:"Panino al prosciutto",      kcal:320, p:16, c:38, f:10,  type:"carb"    },
    { name:"Supplì (1 pz)",             kcal:180, p:6,  c:22, f:8,   type:"carb"    },
    { name:"Arancino (1 pz)",           kcal:280, p:8,  c:38, f:10,  type:"carb"    },
    { name:"Parmigiana di melanzane",   kcal:220, p:9,  c:14, f:14,  type:"fat"     },
    { name:"Quiche lorraine (fetta)",   kcal:330, p:10, c:26, f:21,  type:"fat"     },
    { name:"Kebab in pita",             kcal:480, p:24, c:48, f:20,  type:"carb"    },
    { name:"Sushi misto (8 pz)",        kcal:320, p:14, c:52, f:6,   type:"carb"    },
    { name:"Bowl di riso con salmone",  kcal:420, p:28, c:45, f:12,  type:"protein" },
    { name:"Poke bowl salmone",         kcal:420, p:26, c:48, f:14,  type:"protein" },
  ],
  "Colazione e Snack": [
    { name:"Caffe espresso",            kcal:2,   p:0.1,c:0.3,f:0,   type:"light"   },
    { name:"Caffe macchiato",           kcal:20,  p:0.8,c:2,  f:0.7, type:"light"   },
    { name:"Cappuccino",                kcal:80,  p:4,  c:8,  f:3,   type:"light"   },
    { name:"Latte macchiato",           kcal:110, p:5,  c:12, f:4,   type:"light"   },
    { name:"Tè verde",                  kcal:2,   p:0,  c:0.5,f:0,   type:"light"   },
    { name:"Brioche",                   kcal:250, p:5,  c:38, f:9,   type:"carb"    },
    { name:"Brioche integrale",         kcal:210, p:6,  c:34, f:7,   type:"carb"    },
    { name:"Fette biscottate (2 pz)",   kcal:140, p:3,  c:28, f:2,   type:"carb"    },
    { name:"Yogurt bianco",             kcal:61,  p:3.5,c:7,  f:1.5, type:"light"   },
    { name:"Biscotti (3)",              kcal:150, p:2,  c:23, f:6,   type:"carb"    },
    { name:"Muesli (50g)",              kcal:190, p:5,  c:34, f:4,   type:"carb"    },
    { name:"Granola (50g)",             kcal:220, p:5,  c:35, f:7,   type:"carb"    },
    { name:"Nutella (20g)",             kcal:110, p:1.4,c:12, f:6.5, type:"fat"     },
    { name:"Marmellata (20g)",          kcal:50,  p:0.2,c:13, f:0,   type:"carb"    },
    { name:"Burro di arachidi (20g)",   kcal:120, p:5,  c:4,  f:10,  type:"fat"     },
    { name:"Barretta proteica",         kcal:200, p:20, c:20, f:5,   type:"protein" },
    { name:"Barretta cioccolato",       kcal:160, p:2,  c:18, f:9,   type:"fat"     },
    { name:"Cioccolato fondente (30g)", kcal:170, p:2.5,c:18, f:10,  type:"fat"     },
    { name:"Gelato (1 pallina)",        kcal:130, p:2,  c:18, f:6,   type:"fat"     },
    { name:"Patatine (30g)",            kcal:163, p:2,  c:15, f:11,  type:"fat"     },
    { name:"Frutta secca (30g)",        kcal:180, p:5,  c:6,  f:16,  type:"fat"     },
    { name:"Pistacchi (30g)",           kcal:175, p:6,  c:8,  f:14,  type:"fat"     },
    { name:"Mandorle (30g)",            kcal:175, p:6,  c:6,  f:15,  type:"fat"     },
    { name:"Rice cake (2 pz)",          kcal:70,  p:1.5,c:15, f:0.5, type:"carb"    },
    { name:"Yogurt greco proteico (170g)", kcal:110, p:17, c:6,  f:1.5, type:"protein" },
    { name:"Fiocchi d'avena con frutta (200ml)", kcal:210, p:7,  c:36, f:4, type:"carb" },
    { name:"Torta di mele (fetta)",     kcal:280, p:4,  c:42, f:11,  type:"carb"    },
    { name:"Tiramisù (porzione)",       kcal:380, p:7,  c:38, f:22,  type:"fat"     },
    { name:"Panna cotta",               kcal:220, p:3,  c:25, f:12,  type:"fat"     },
    { name:"Pancake (2)",               kcal:220, p:6,  c:34, f:7,   type:"carb"    },
    { name:"Porridge alla frutta",      kcal:230, p:7,  c:38, f:5,   type:"carb"    },
    { name:"Skyr naturale (150g)",      kcal:95,  p:16, c:6,  f:0.3, type:"protein" },
  ],
  "Bevande": [
    { name:"Acqua",                     kcal:0,   p:0,  c:0,  f:0,   type:"light"   },
    { name:"Acqua frizzante",           kcal:0,   p:0,  c:0,  f:0,   type:"light"   },
    { name:"Succo arancia (200ml)",     kcal:90,  p:1,  c:22, f:0,   type:"carb"    },
    { name:"Succo mela (200ml)",        kcal:96,  p:0.3,c:24, f:0,   type:"carb"    },
    { name:"Smoothie frutta (200ml)",   kcal:120, p:1,  c:28, f:0.5, type:"carb"    },
    { name:"Coca Cola (330ml)",         kcal:139, p:0,  c:35, f:0,   type:"carb"    },
    { name:"Coca Cola Zero (330ml)",    kcal:1,   p:0,  c:0,  f:0,   type:"light"   },
    { name:"Aranciata (330ml)",         kcal:130, p:0,  c:33, f:0,   type:"carb"    },
    { name:"Birra (330ml)",             kcal:143, p:1,  c:13, f:0,   type:"carb"    },
    { name:"Birra artigianale (330ml)", kcal:180, p:2,  c:18, f:0,   type:"carb"    },
    { name:"Vino rosso (150ml)",        kcal:127, p:0.1,c:4,  f:0,   type:"light"   },
    { name:"Vino bianco (150ml)",       kcal:121, p:0.1,c:3.5,f:0,   type:"light"   },
    { name:"Prosecco (150ml)",          kcal:108, p:0.3,c:3,  f:0,   type:"light"   },
    { name:"Lambrusco (150ml)",         kcal:90,  p:0.1,c:5,  f:0,   type:"light"   },
    { name:"Spritz (200ml)",            kcal:120, p:0,  c:8,  f:0,   type:"light"   },
    { name:"Latte di avena (200ml)",    kcal:90,  p:2,  c:16, f:2,   type:"carb"    },
    { name:"Latte di soia (200ml)",     kcal:80,  p:6,  c:7,  f:3,   type:"protein" },
    { name:"Latte di mandorla (200ml)", kcal:50,  p:1,  c:7,  f:2,   type:"light"   },
    { name:"Protein shake (300ml)",     kcal:180, p:30, c:8,  f:3,   type:"protein" },
    { name:"Chinotto (330ml)",          kcal:120, p:0,  c:30, f:0,   type:"carb"    },
    { name:"Tè freddo limone (330ml)",  kcal:110, p:0,  c:27, f:0,   type:"carb"    },
    { name:"Kombucha (250ml)",          kcal:55,  p:0,  c:14, f:0,   type:"light"   },
    { name:"Acqua di cocco (250ml)",    kcal:60,  p:1,  c:14, f:0,   type:"light"   },
    { name:"Tè verde (250ml)",          kcal:2,   p:0,  c:0.5,f:0,   type:"light"   },
  ],
};
 
export const ALL_FOODS = Object.entries(FOOD_DB).flatMap(([cat,items]) =>
  items.map(f => ({ ...f, _cat: cat }))
);
 

