// ─────────────────────────────────────────────────────────────────────────────
// FoodDB.js — v1.9.6
//
// Database alimenti e derivazione ALL_FOODS, estratti da useNutriFox.js dove
// erano già isolati e pronti per questo passaggio fin dalla v1.4.1. Nessun
// dato cambiato, solo spostato: questo file non contiene alcuna logica,
// solo dati e la derivazione piatta usata per ricerca/filtri.
//
// v1.9: +10 alimenti (249 totali) mirati a completare i pool usati dal nuovo
// Meal Builder intelligente — contorni/verdure, cereali "carb", proteine
// magre pronte e opzioni bilanciate per colazione/spuntino.
//
// v1.9.1: +3 alimenti (252 totali) — salmone al forno e ceci in insalata
// (altre proteine per il Meal Builder), tè verde.
//
// v1.9.2: +2 alimenti (254 totali) — orzo perlato (varietà nel pool "carb"
// del Meal Builder ora iterativo, utile quando si sostituisce/rigenera) e
// fiocchi di latte (proteina leggera per colazione/spuntino).
//
// v1.9.3: +2 alimenti (256 totali) — muesli con frutta secca e kiwi, scelti
// per avere più coppie plausibili da riconoscere come "combinazioni
// ricorrenti" nella memoria alimentare arricchita di questa versione.
//
// v1.9.4: FoodDB più strutturato. Ogni alimento guadagna 7 nuovi campi:
//   - fibra, zuccheri, sale (grammi)
//   - gruppo (gruppo alimentare: Carne, Pesce, Salumi, Latticini, Uova,
//     Cereali, Verdura, Legumi, Frutta, Condimenti, Surgelati, Piatti pronti,
//     Dolci e Snack, Bevande)
//   - vegetariano, vegano (booleani)
//   - sazieta ("basso"/"medio"/"alto")
//   - pasti (array dei pasti consigliati: Colazione/Pranzo/Cena/Spuntino,
//     allineato a MEAL_TYPE_POOLS in useNutriFox.js)
//
// IMPORTANTE: fibra/zuccheri/sale/sazieta sono stime euristiche calcolate da
// uno script deterministico (categoria + parole chiave nel nome + macro
// esistenti), NON valori nutrizionali certificati da una fonte ufficiale.
// gruppo/vegetariano/vegano/pasti sono classificazioni automatiche con la
// stessa logica — accurate nella maggioranza dei casi ma non verificate uno
// per uno su 256 alimenti. Nessuno di questi campi è ancora consultato da
// alcuna logica dell'app: sono predisposizione strutturale, come richiesto,
// perfezionabili singolarmente quando verranno effettivamente usati.
//
// v1.9.5: +2 alimenti (258 totali) — camomilla e succo di mirtillo, con lo
// schema di metadati completo introdotto in v1.9.4.
//
// v1.9.6: +1 alimento (259 totali) — tisana ai frutti di bosco. Questa
// versione ha riorganizzato solo useNutriFox.js (pulizia strutturale in 6
// sezioni); FoodDB.js non ha altri cambiamenti oltre al nuovo alimento.
// ─────────────────────────────────────────────────────────────────────────────

export const FOOD_DB = {
  "Carne e Pesce": [
    { name:"Petto di pollo", kcal:165, p:31, c:0, f:3.6, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Coscia di pollo", kcal:215, p:26, c:0, f:12, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pollo arrosto", kcal:239, p:27, c:0, f:14, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Bistecca di manzo", kcal:250, p:26, c:0, f:16, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Macinato di manzo", kcal:280, p:25, c:0, f:20, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Lonza di maiale", kcal:185, p:29, c:0, f:7, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Fesa di tacchino", kcal:135, p:29, c:0, f:1.5, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Agnello (coscia)", kcal:258, p:25, c:0, f:17, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Salmone al forno", kcal:208, p:28, c:0, f:10, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Tonno in scatola", kcal:130, p:28, c:0, f:1.5, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Merluzzo", kcal:82, p:18, c:0, f:0.7, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Orata al forno", kcal:120, p:22, c:0, f:3.5, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Branzino al forno", kcal:115, p:21, c:0, f:3.2, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Sgombro in scatola", kcal:200, p:19, c:0, f:14, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Alici sott'olio (50g)", kcal:95, p:13, c:0, f:5, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Polpo lessato", kcal:82, p:15, c:2, f:1, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Seppie", kcal:79, p:16, c:0.8, f:1, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Gamberetti", kcal:99, p:20, c:0.9, f:1.7, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Cozze (100g)", kcal:86, p:12, c:3.7, f:2.2, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Prosciutto cotto", kcal:130, p:19, c:1, f:5.5, type:"protein", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Prosciutto di Parma", kcal:90, p:7, c:0, f:7, type:"protein", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Culatello", kcal:95, p:8, c:0, f:7, type:"protein", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Bresaola", kcal:98, p:21, c:0, f:1.5, type:"protein", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Mortadella Bologna", kcal:155, p:7.5, c:0.5, f:14, type:"fat", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Salsiccia", kcal:302, p:13, c:2, f:27, type:"fat", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Cotechino (porzione)", kcal:320, p:14, c:1, f:29, type:"fat", fibra:0, zuccheri:0, sale:2.2, gruppo:"Salumi", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Cotoletta alla bolognese", kcal:380, p:28, c:12, f:24, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Spezzatino di manzo", kcal:210, p:24, c:4, f:10, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Polpette al sugo (3)", kcal:280, p:18, c:12, f:17, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pollo alla cacciatora", kcal:260, p:28, c:6, f:14, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Tonno alla griglia", kcal:200, p:34, c:0, f:7, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Petto di tacchino grigliato", kcal:150, p:32, c:0, f:1.8, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Ceviche di pesce (100g)", kcal:110, p:18, c:4, f:2, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Involtini di pollo (2 pz)", kcal:220, p:26, c:4, f:11, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Filetto di merluzzo al vapore", kcal:90, p:19, c:0, f:1, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Straccetti di manzo (100g)", kcal:190, p:27, c:0, f:9, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Hamburger di manzo al naturale (100g)", kcal:215, p:26, c:0, f:12, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Petto di pollo alla piastra (100g)", kcal:160, p:31, c:0, f:3.2, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Bocconcini di tacchino saltati (100g)", kcal:145, p:30, c:0, f:2, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Carne", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Salmone al forno (100g)", kcal:206, p:22, c:0, f:13, type:"protein", fibra:0, zuccheri:0, sale:0.15, gruppo:"Pesce", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
  ],
  "Uova e Latticini": [
    { name:"Uovo intero", kcal:78, p:6, c:0.6, f:5, type:"protein", fibra:0, zuccheri:0.1, sale:0.12, gruppo:"Uova", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Uova strapazzate (2)", kcal:180, p:14, c:1, f:13, type:"protein", fibra:0, zuccheri:0.1, sale:0.12, gruppo:"Uova", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Frittata (2 uova)", kcal:210, p:14, c:2, f:16, type:"protein", fibra:0, zuccheri:0.2, sale:0.12, gruppo:"Uova", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Uova sode (2)", kcal:156, p:12, c:1, f:11, type:"protein", fibra:0, zuccheri:0.1, sale:0.12, gruppo:"Uova", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Mozzarella", kcal:280, p:18, c:2, f:22, type:"fat", fibra:0, zuccheri:0.2, sale:0.9, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Parmigiano Reggiano", kcal:119, p:10, c:0, f:8.5, type:"protein", fibra:0, zuccheri:0, sale:1.6, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Grana Padano", kcal:114, p:10, c:0, f:8, type:"protein", fibra:0, zuccheri:0, sale:1.6, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Pecorino (30g)", kcal:120, p:8, c:0.5, f:10, type:"fat", fibra:0, zuccheri:0.1, sale:1.6, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Ricotta", kcal:174, p:11, c:3, f:13, type:"fat", fibra:0, zuccheri:0.3, sale:0.9, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Squacquerone (50g)", kcal:130, p:6, c:1, f:11, type:"fat", fibra:0, zuccheri:0.1, sale:0.9, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Stracchino (50g)", kcal:120, p:7, c:0.5, f:10, type:"fat", fibra:0, zuccheri:0.1, sale:0.9, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Yogurt greco", kcal:100, p:10, c:6, f:3, type:"protein", fibra:0, zuccheri:5.1, sale:0.12, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Yogurt bianco", kcal:61, p:3.5, c:7, f:1.5, type:"light", fibra:0, zuccheri:6, sale:0.12, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Kefir (200ml)", kcal:90, p:6, c:9, f:2.5, type:"protein", fibra:0, zuccheri:7.7, sale:0.12, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Latte intero (200ml)", kcal:130, p:6.6, c:9.6, f:7.4, type:"fat", fibra:0, zuccheri:8.2, sale:0.12, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Latte scremato (200ml)", kcal:70, p:6.8, c:9.8, f:0.2, type:"light", fibra:0, zuccheri:8.3, sale:0.12, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Burrata", kcal:330, p:15, c:2, f:30, type:"fat", fibra:0, zuccheri:0.2, sale:0.9, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
    { name:"Fiocchi di latte (100g)", kcal:98, p:12, c:3, f:4.3, type:"protein", fibra:0, zuccheri:2.6, sale:0.12, gruppo:"Latticini", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino","Pranzo","Cena"] },
  ],
  "Pasta e Cereali": [
    { name:"Pasta al pomodoro", kcal:350, p:12, c:65, f:5, type:"carb", fibra:2.5, zuccheri:2.6, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta in bianco", kcal:290, p:10, c:58, f:3, type:"carb", fibra:2.5, zuccheri:2.3, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta al pesto", kcal:420, p:12, c:60, f:16, type:"carb", fibra:2.5, zuccheri:2.4, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta alla norma", kcal:380, p:10, c:62, f:11, type:"carb", fibra:2.5, zuccheri:2.5, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta al ragu", kcal:450, p:20, c:58, f:15, type:"carb", fibra:2.5, zuccheri:2.3, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta e fagioli", kcal:280, p:14, c:45, f:5, type:"carb", fibra:2.5, zuccheri:1.8, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta e ceci", kcal:290, p:13, c:48, f:4, type:"carb", fibra:2.5, zuccheri:1.9, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Tagliatelle al ragu", kcal:480, p:22, c:52, f:18, type:"carb", fibra:2.5, zuccheri:2.1, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Tortellini in brodo", kcal:320, p:14, c:42, f:10, type:"carb", fibra:2.5, zuccheri:1.7, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Tortellini panna e prosciutto", kcal:520, p:18, c:48, f:26, type:"fat", fibra:2.5, zuccheri:1.9, sale:2.2, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Lasagne verdi bolognese", kcal:420, p:20, c:38, f:20, type:"carb", fibra:2.5, zuccheri:1.5, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Spaghetti alle vongole", kcal:380, p:18, c:58, f:9, type:"carb", fibra:2.5, zuccheri:2.3, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Riso bollito", kcal:130, p:2.7, c:28, f:0.3, type:"carb", fibra:2.5, zuccheri:1.1, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Riso integrale", kcal:150, p:3.5, c:30, f:1.5, type:"carb", fibra:6, zuccheri:1.2, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Risotto ai funghi", kcal:320, p:8, c:52, f:9, type:"carb", fibra:2.5, zuccheri:2.1, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Risotto allo zafferano", kcal:340, p:8, c:55, f:10, type:"carb", fibra:2.5, zuccheri:2.2, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Risotto ai gamberetti", kcal:360, p:16, c:52, f:9, type:"carb", fibra:2.5, zuccheri:2.1, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Gnocchi al pomodoro", kcal:310, p:8, c:58, f:5, type:"carb", fibra:2.5, zuccheri:2.3, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pane bianco", kcal:134, p:4, c:27, f:0.9, type:"carb", fibra:2.5, zuccheri:1.1, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Pane integrale", kcal:120, p:5, c:22, f:1.5, type:"carb", fibra:6, zuccheri:0.9, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pane di segale", kcal:110, p:4.5, c:20, f:1, type:"carb", fibra:2.5, zuccheri:0.8, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Focaccia (100g)", kcal:280, p:7, c:40, f:9, type:"carb", fibra:2.5, zuccheri:1.6, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Piadina romagnola", kcal:290, p:7, c:42, f:10, type:"carb", fibra:2.5, zuccheri:1.7, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Gnocco fritto", kcal:340, p:6, c:38, f:18, type:"fat", fibra:2.5, zuccheri:1.5, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Tigella", kcal:220, p:6, c:32, f:8, type:"carb", fibra:2.5, zuccheri:1.3, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Polenta (100g)", kcal:83, p:2, c:18, f:0.5, type:"carb", fibra:2.5, zuccheri:0.7, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Farro (100g cotto)", kcal:150, p:6, c:30, f:1, type:"carb", fibra:6, zuccheri:1.2, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Orzo (100g cotto)", kcal:123, p:3, c:25, f:0.4, type:"carb", fibra:6, zuccheri:1, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Quinoa (100g cotta)", kcal:120, p:4.4, c:22, f:1.9, type:"carb", fibra:6, zuccheri:0.9, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Avena (porridge 200ml)", kcal:150, p:5, c:27, f:3, type:"carb", fibra:6, zuccheri:1.1, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Crackers (5 pz)", kcal:110, p:2.5, c:18, f:3.5, type:"carb", fibra:1, zuccheri:0.7, sale:1, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Pasta alla carbonara", kcal:460, p:18, c:55, f:18, type:"carb", fibra:2.5, zuccheri:2.2, sale:0.4, gruppo:"Cereali", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pasta integrale al pomodoro", kcal:310, p:12, c:56, f:3, type:"carb", fibra:6, zuccheri:2.2, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Riso basmati (100g cotto)", kcal:135, p:2.9, c:29, f:0.3, type:"carb", fibra:2.5, zuccheri:1.2, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Cous cous (100g cotto)", kcal:112, p:3.8, c:23, f:0.2, type:"carb", fibra:2.5, zuccheri:0.9, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Orzo perlato (100g cotto)", kcal:123, p:2.3, c:28, f:0.4, type:"carb", fibra:6, zuccheri:1.1, sale:0.4, gruppo:"Cereali", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
  ],
  "Verdure e Legumi": [
    { name:"Insalata mista", kcal:15, p:1, c:2, f:0.2, type:"light", fibra:2.8, zuccheri:0.4, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Pomodori (100g)", kcal:18, p:0.9, c:3.5, f:0.2, type:"light", fibra:2.8, zuccheri:0.6, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Zucchine", kcal:17, p:1.2, c:3.1, f:0.3, type:"light", fibra:2.8, zuccheri:0.6, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Melanzane", kcal:25, p:1, c:6, f:0.2, type:"light", fibra:2.8, zuccheri:1.1, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Peperoni", kcal:31, p:1, c:6, f:0.3, type:"light", fibra:2.8, zuccheri:1.1, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Spinaci", kcal:23, p:2.9, c:3.6, f:0.4, type:"light", fibra:2.8, zuccheri:0.6, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Broccoli", kcal:34, p:2.8, c:7, f:0.4, type:"light", fibra:2.8, zuccheri:1.3, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Cavolfiore", kcal:25, p:1.9, c:5, f:0.3, type:"light", fibra:2.8, zuccheri:0.9, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Carote (100g)", kcal:41, p:0.9, c:10, f:0.2, type:"light", fibra:2.8, zuccheri:1.8, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Asparagi (100g)", kcal:20, p:2.2, c:3.7, f:0.2, type:"light", fibra:2.8, zuccheri:0.7, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Carciofi (100g)", kcal:47, p:3.3, c:10, f:0.2, type:"light", fibra:2.8, zuccheri:1.8, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Fagiolini (100g)", kcal:31, p:1.8, c:7, f:0.2, type:"light", fibra:6.5, zuccheri:1.3, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Funghi champignon", kcal:22, p:3, c:4, f:0.3, type:"light", fibra:2.8, zuccheri:0.7, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Funghi porcini", kcal:28, p:3.7, c:4.3, f:0.5, type:"light", fibra:2.8, zuccheri:0.8, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Rucola (50g)", kcal:20, p:2.5, c:2, f:0.7, type:"light", fibra:2.8, zuccheri:0.4, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Rape rosse cotte", kcal:43, p:1.6, c:10, f:0.2, type:"light", fibra:2.8, zuccheri:1.8, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Cavolo cappuccio (100g)", kcal:25, p:1.3, c:6, f:0.1, type:"light", fibra:2.8, zuccheri:1.1, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Ceci cotti", kcal:164, p:8.9, c:27, f:2.6, type:"carb", fibra:6.5, zuccheri:4.9, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Lenticchie cotte", kcal:116, p:9, c:20, f:0.4, type:"protein", fibra:6.5, zuccheri:3.6, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Fagioli borlotti (100g)", kcal:128, p:8.7, c:21, f:0.5, type:"protein", fibra:6.5, zuccheri:3.8, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Fagioli cannellini (100g)", kcal:120, p:9, c:20, f:0.5, type:"protein", fibra:6.5, zuccheri:3.6, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Piselli (100g)", kcal:81, p:5, c:14, f:0.4, type:"carb", fibra:5, zuccheri:2.5, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Edamame (100g)", kcal:122, p:11, c:10, f:5, type:"protein", fibra:6.5, zuccheri:1.8, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Patate lesse (100g)", kcal:77, p:2, c:17, f:0.1, type:"carb", fibra:2.8, zuccheri:3.1, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Patate al forno", kcal:150, p:3, c:30, f:3, type:"carb", fibra:2.8, zuccheri:5.4, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Minestrone", kcal:85, p:4, c:14, f:1.5, type:"light", fibra:2.8, zuccheri:2.5, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Passata di pomodoro (100g)", kcal:24, p:1.1, c:5, f:0.2, type:"light", fibra:2.8, zuccheri:0.9, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Erbazzone", kcal:220, p:8, c:22, f:11, type:"fat", fibra:2.8, zuccheri:4, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Zuppa di lenticchie", kcal:140, p:9, c:22, f:2, type:"protein", fibra:6.5, zuccheri:4, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Caponata (100g)", kcal:90, p:1.5, c:9, f:5, type:"light", fibra:2.8, zuccheri:1.6, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Melanzane a funghetto", kcal:90, p:2, c:8, f:6, type:"light", fibra:2.8, zuccheri:1.4, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Zucca al forno (150g)", kcal:65, p:1.5, c:14, f:0.3, type:"light", fibra:2.8, zuccheri:2.5, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Hummus di ceci fatto in casa (50g)", kcal:120, p:4.5, c:9, f:8, type:"protein", fibra:6.5, zuccheri:1.6, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Insalata di finocchi e arance (150g)", kcal:60, p:1.5, c:13, f:0.3, type:"light", fibra:2.8, zuccheri:2.3, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Verdure grigliate miste (150g)", kcal:70, p:2, c:9, f:2.5, type:"light", fibra:2.8, zuccheri:1.6, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Puré di patate (100g)", kcal:105, p:2, c:16, f:3.5, type:"carb", fibra:2.8, zuccheri:2.9, sale:0.03, gruppo:"Verdura", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Ceci in insalata (100g)", kcal:120, p:7, c:18, f:2, type:"protein", fibra:6.5, zuccheri:3.2, sale:0.03, gruppo:"Legumi", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
  ],
  "Frutta": [
    { name:"Mela", kcal:72, p:0.4, c:19, f:0.2, type:"light", fibra:2.3, zuccheri:15.6, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Banana", kcal:105, p:1.3, c:27, f:0.4, type:"carb", fibra:2.3, zuccheri:22.1, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Arancia", kcal:62, p:1.2, c:15, f:0.2, type:"light", fibra:2.3, zuccheri:12.3, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Mandarino (2 pz)", kcal:70, p:1, c:17, f:0.3, type:"light", fibra:2.3, zuccheri:13.9, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Pera", kcal:57, p:0.4, c:15, f:0.1, type:"light", fibra:2.3, zuccheri:12.3, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Pesca", kcal:39, p:0.9, c:10, f:0.3, type:"light", fibra:2.3, zuccheri:8.2, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Albicocche (2 pz)", kcal:48, p:1.4, c:11, f:0.4, type:"light", fibra:2.3, zuccheri:9, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Fragole (100g)", kcal:32, p:0.7, c:8, f:0.3, type:"light", fibra:2.3, zuccheri:6.6, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Ciliegie (100g)", kcal:63, p:1, c:16, f:0.2, type:"light", fibra:2.3, zuccheri:13.1, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Uva (100g)", kcal:69, p:0.7, c:18, f:0.2, type:"light", fibra:2.3, zuccheri:14.8, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Kiwi", kcal:61, p:1.1, c:15, f:0.5, type:"light", fibra:2.3, zuccheri:12.3, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Mango (100g)", kcal:60, p:0.8, c:15, f:0.4, type:"light", fibra:2.3, zuccheri:12.3, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Ananas (100g)", kcal:50, p:0.5, c:13, f:0.1, type:"light", fibra:2.3, zuccheri:10.7, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Anguria (200g)", kcal:60, p:1.2, c:15, f:0.2, type:"light", fibra:2.3, zuccheri:12.3, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Melone (200g)", kcal:68, p:1.7, c:16, f:0.3, type:"light", fibra:2.3, zuccheri:13.1, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Lamponi (100g)", kcal:52, p:1.2, c:12, f:0.7, type:"light", fibra:5, zuccheri:9.8, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Mirtilli (100g)", kcal:57, p:0.7, c:14, f:0.3, type:"light", fibra:5, zuccheri:11.5, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Avocado", kcal:160, p:2, c:9, f:15, type:"fat", fibra:7, zuccheri:7.4, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Frutto della passione (2)", kcal:48, p:2, c:11, f:0.4, type:"light", fibra:2.3, zuccheri:9, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Fico (2 pz)", kcal:74, p:0.8, c:19, f:0.3, type:"light", fibra:5, zuccheri:15.6, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Cocco (30g)", kcal:106, p:1, c:4, f:10, type:"fat", fibra:2.3, zuccheri:3.3, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Kiwi (2 pz)", kcal:84, p:1.6, c:20, f:0.6, type:"light", fibra:2.3, zuccheri:16.4, sale:0.03, gruppo:"Frutta", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
  ],
  "Sughi e Condimenti": [
    { name:"Sugo al pomodoro (100g)", kcal:45, p:1.5, c:8, f:1.2, type:"light", fibra:0.8, zuccheri:1.2, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Sugo all'arrabbiata", kcal:55, p:1.5, c:8, f:2.5, type:"light", fibra:0.8, zuccheri:1.2, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Ragu bolognese (100g)", kcal:150, p:10, c:6, f:10, type:"protein", fibra:0.8, zuccheri:0.9, sale:0.5, gruppo:"Condimenti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pesto alla genovese (30g)", kcal:130, p:2.5, c:1.5, f:13, type:"fat", fibra:0.8, zuccheri:0.2, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Besciamella (50ml)", kcal:72, p:2, c:5, f:5, type:"fat", fibra:0.8, zuccheri:0.8, sale:0.8, gruppo:"Condimenti", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Olio d'oliva (10ml)", kcal:90, p:0, c:0, f:10, type:"fat", fibra:0.8, zuccheri:0, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Burro (10g)", kcal:74, p:0.1, c:0, f:8.3, type:"fat", fibra:0.8, zuccheri:0, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Aceto balsamico (15ml)", kcal:21, p:0.2, c:5, f:0, type:"light", fibra:0.8, zuccheri:0.8, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Maionese (15g)", kcal:104, p:0.2, c:0.3, f:11, type:"fat", fibra:0.8, zuccheri:0, sale:0.8, gruppo:"Condimenti", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Salsa di soia (15ml)", kcal:9, p:1.3, c:0.9, f:0, type:"light", fibra:0.8, zuccheri:0.1, sale:5.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Hummus (50g)", kcal:115, p:4, c:9, f:7, type:"protein", fibra:3, zuccheri:1.3, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Guacamole (50g)", kcal:80, p:1, c:4, f:7, type:"fat", fibra:3, zuccheri:0.6, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Tzatziki (50g)", kcal:55, p:3, c:3, f:3, type:"light", fibra:0.8, zuccheri:0.5, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Salsa BBQ (30g)", kcal:60, p:0.3, c:14, f:0.2, type:"carb", fibra:0.8, zuccheri:8.4, sale:0.5, gruppo:"Condimenti", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
  ],
  "Surgelati": [
    { name:"Bastoncini di pesce (2)", kcal:160, p:8, c:16, f:7, type:"carb", fibra:1.2, zuccheri:1.3, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Sofficini (2)", kcal:280, p:8, c:30, f:14, type:"carb", fibra:1.2, zuccheri:2.4, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Lasagne surgelate", kcal:380, p:18, c:38, f:16, type:"carb", fibra:1.2, zuccheri:3, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Cannelloni surgelati", kcal:290, p:14, c:28, f:13, type:"carb", fibra:1.2, zuccheri:2.2, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pizza surgelata (meta)", kcal:420, p:14, c:54, f:16, type:"carb", fibra:1.2, zuccheri:4.3, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Crocchette pollo (3)", kcal:220, p:12, c:18, f:11, type:"protein", fibra:1.2, zuccheri:1.4, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Cotolette di pesce", kcal:180, p:10, c:14, f:9, type:"protein", fibra:1.2, zuccheri:1.1, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Cordon bleu (1 pz)", kcal:280, p:16, c:16, f:16, type:"protein", fibra:1.2, zuccheri:1.3, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Minestrone surgelato", kcal:60, p:3, c:11, f:0.5, type:"light", fibra:3, zuccheri:0.9, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Spinaci surgelati", kcal:22, p:2.8, c:2, f:0.4, type:"light", fibra:3, zuccheri:0.2, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Verdure miste surgelate", kcal:45, p:3, c:8, f:0.5, type:"light", fibra:3, zuccheri:0.6, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Patatine fritte surgelate", kcal:270, p:3.5, c:36, f:13, type:"carb", fibra:1.2, zuccheri:2.9, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Pranzo","Cena"] },
    { name:"Wurstel", kcal:120, p:5, c:1, f:11, type:"fat", fibra:1.2, zuccheri:0.1, sale:2.2, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Tortellini surgelati", kcal:340, p:15, c:44, f:11, type:"carb", fibra:1.2, zuccheri:3.5, sale:1.1, gruppo:"Surgelati", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Burger di soia surgelato", kcal:180, p:16, c:14, f:6, type:"protein", fibra:1.2, zuccheri:1.1, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Edamame surgelato (100g)", kcal:122, p:11, c:10, f:5, type:"protein", fibra:3, zuccheri:0.8, sale:1.1, gruppo:"Surgelati", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
  ],
  "Piatti pronti": [
    { name:"Pizza margherita (fetta)", kcal:270, p:11, c:35, f:9, type:"carb", fibra:1.5, zuccheri:4.2, sale:1.1, gruppo:"Piatti pronti", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pizza 4 stagioni (fetta)", kcal:290, p:13, c:33, f:11, type:"carb", fibra:1.5, zuccheri:4, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Pizza bianca (100g)", kcal:310, p:9, c:48, f:9, type:"carb", fibra:1.5, zuccheri:5.8, sale:1.1, gruppo:"Piatti pronti", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Hamburger classico", kcal:480, p:26, c:40, f:24, type:"fat", fibra:1.5, zuccheri:4.8, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Piadina squacquerone", kcal:480, p:14, c:52, f:24, type:"fat", fibra:1.5, zuccheri:6.2, sale:1.1, gruppo:"Piatti pronti", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Piadina prosciutto rucola", kcal:440, p:18, c:46, f:20, type:"carb", fibra:1.5, zuccheri:5.5, sale:2.2, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Tramezzino tonno", kcal:350, p:14, c:42, f:13, type:"carb", fibra:1.5, zuccheri:5, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Panino al prosciutto", kcal:320, p:16, c:38, f:10, type:"carb", fibra:1.5, zuccheri:4.6, sale:2.2, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Supplì (1 pz)", kcal:180, p:6, c:22, f:8, type:"carb", fibra:1.5, zuccheri:2.6, sale:1.1, gruppo:"Piatti pronti", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Arancino (1 pz)", kcal:280, p:8, c:38, f:10, type:"carb", fibra:1.5, zuccheri:4.6, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"medio", pasti:["Pranzo","Cena"] },
    { name:"Parmigiana di melanzane", kcal:220, p:9, c:14, f:14, type:"fat", fibra:2, zuccheri:1.7, sale:1.1, gruppo:"Piatti pronti", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Quiche lorraine (fetta)", kcal:330, p:10, c:26, f:21, type:"fat", fibra:1.5, zuccheri:3.1, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Kebab in pita", kcal:480, p:24, c:48, f:20, type:"carb", fibra:1.5, zuccheri:5.8, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Sushi misto (8 pz)", kcal:320, p:14, c:52, f:6, type:"carb", fibra:1.5, zuccheri:6.2, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Bowl di riso con salmone", kcal:420, p:28, c:45, f:12, type:"protein", fibra:2, zuccheri:5.4, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
    { name:"Poke bowl salmone", kcal:420, p:26, c:48, f:14, type:"protein", fibra:2, zuccheri:5.8, sale:1.1, gruppo:"Piatti pronti", vegetariano:false, vegano:false, sazieta:"alto", pasti:["Pranzo","Cena"] },
  ],
  "Colazione e Snack": [
    { name:"Caffe espresso", kcal:2, p:0.1, c:0.3, f:0, type:"light", fibra:1.2, zuccheri:0.1, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Caffe macchiato", kcal:20, p:0.8, c:2, f:0.7, type:"light", fibra:1.2, zuccheri:0.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Cappuccino", kcal:80, p:4, c:8, f:3, type:"light", fibra:1.2, zuccheri:2, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Latte macchiato", kcal:110, p:5, c:12, f:4, type:"light", fibra:1.2, zuccheri:3, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Tè verde", kcal:2, p:0, c:0.5, f:0, type:"light", fibra:1.2, zuccheri:0.1, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Brioche", kcal:250, p:5, c:38, f:9, type:"carb", fibra:1.2, zuccheri:9.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Brioche integrale", kcal:210, p:6, c:34, f:7, type:"carb", fibra:1.2, zuccheri:8.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Fette biscottate (2 pz)", kcal:140, p:3, c:28, f:2, type:"carb", fibra:1.2, zuccheri:7, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Yogurt bianco", kcal:61, p:3.5, c:7, f:1.5, type:"light", fibra:1.2, zuccheri:1.8, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Biscotti (3)", kcal:150, p:2, c:23, f:6, type:"carb", fibra:1.2, zuccheri:12.7, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Muesli (50g)", kcal:190, p:5, c:34, f:4, type:"carb", fibra:4.5, zuccheri:8.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Granola (50g)", kcal:220, p:5, c:35, f:7, type:"carb", fibra:4.5, zuccheri:8.8, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Nutella (20g)", kcal:110, p:1.4, c:12, f:6.5, type:"fat", fibra:1.2, zuccheri:6.6, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Marmellata (20g)", kcal:50, p:0.2, c:13, f:0, type:"carb", fibra:1.2, zuccheri:7.2, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Burro di arachidi (20g)", kcal:120, p:5, c:4, f:10, type:"fat", fibra:1.2, zuccheri:1, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Barretta proteica", kcal:200, p:20, c:20, f:5, type:"protein", fibra:1.2, zuccheri:5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino"] },
    { name:"Barretta cioccolato", kcal:160, p:2, c:18, f:9, type:"fat", fibra:1.2, zuccheri:9.9, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Cioccolato fondente (30g)", kcal:170, p:2.5, c:18, f:10, type:"fat", fibra:1.2, zuccheri:9.9, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Gelato (1 pallina)", kcal:130, p:2, c:18, f:6, type:"fat", fibra:1.2, zuccheri:9.9, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Patatine (30g)", kcal:163, p:2, c:15, f:11, type:"fat", fibra:1.2, zuccheri:3.8, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Frutta secca (30g)", kcal:180, p:5, c:6, f:16, type:"fat", fibra:4.5, zuccheri:1.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Pistacchi (30g)", kcal:175, p:6, c:8, f:14, type:"fat", fibra:4.5, zuccheri:2, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Colazione","Spuntino"] },
    { name:"Mandorle (30g)", kcal:175, p:6, c:6, f:15, type:"fat", fibra:4.5, zuccheri:1.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Colazione","Spuntino"] },
    { name:"Rice cake (2 pz)", kcal:70, p:1.5, c:15, f:0.5, type:"carb", fibra:1.2, zuccheri:3.8, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Yogurt greco proteico (170g)", kcal:110, p:17, c:6, f:1.5, type:"protein", fibra:1.2, zuccheri:1.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"alto", pasti:["Colazione","Spuntino"] },
    { name:"Fiocchi d'avena con frutta (200ml)", kcal:210, p:7, c:36, f:4, type:"carb", fibra:4.5, zuccheri:9, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Colazione","Spuntino"] },
    { name:"Torta di mele (fetta)", kcal:280, p:4, c:42, f:11, type:"carb", fibra:1.2, zuccheri:23.1, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Tiramisù (porzione)", kcal:380, p:7, c:38, f:22, type:"fat", fibra:1.2, zuccheri:20.9, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Panna cotta", kcal:220, p:3, c:25, f:12, type:"fat", fibra:1.2, zuccheri:13.8, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"basso", pasti:["Colazione","Spuntino"] },
    { name:"Pancake (2)", kcal:220, p:6, c:34, f:7, type:"carb", fibra:1.2, zuccheri:8.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Porridge alla frutta", kcal:230, p:7, c:38, f:5, type:"carb", fibra:1.2, zuccheri:9.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Spuntino"] },
    { name:"Skyr naturale (150g)", kcal:95, p:16, c:6, f:0.3, type:"protein", fibra:1.2, zuccheri:1.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Colazione","Spuntino"] },
    { name:"Muesli con frutta secca (60g)", kcal:245, p:6, c:38, f:8, type:"carb", fibra:4.5, zuccheri:9.5, sale:0.3, gruppo:"Dolci e Snack", vegetariano:true, vegano:false, sazieta:"medio", pasti:["Colazione","Spuntino"] },
  ],
  "Bevande": [
    { name:"Acqua", kcal:0, p:0, c:0, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Acqua frizzante", kcal:0, p:0, c:0, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Succo arancia (200ml)", kcal:90, p:1, c:22, f:0, type:"carb", fibra:0, zuccheri:19.8, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Succo mela (200ml)", kcal:96, p:0.3, c:24, f:0, type:"carb", fibra:0, zuccheri:21.6, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Smoothie frutta (200ml)", kcal:120, p:1, c:28, f:0.5, type:"carb", fibra:1, zuccheri:25.2, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Coca Cola (330ml)", kcal:139, p:0, c:35, f:0, type:"carb", fibra:0, zuccheri:31.5, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Coca Cola Zero (330ml)", kcal:1, p:0, c:0, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Aranciata (330ml)", kcal:130, p:0, c:33, f:0, type:"carb", fibra:0, zuccheri:29.7, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Birra (330ml)", kcal:143, p:1, c:13, f:0, type:"carb", fibra:0, zuccheri:11.7, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Birra artigianale (330ml)", kcal:180, p:2, c:18, f:0, type:"carb", fibra:0, zuccheri:16.2, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Vino rosso (150ml)", kcal:127, p:0.1, c:4, f:0, type:"light", fibra:0, zuccheri:3.6, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Vino bianco (150ml)", kcal:121, p:0.1, c:3.5, f:0, type:"light", fibra:0, zuccheri:3.2, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Prosecco (150ml)", kcal:108, p:0.3, c:3, f:0, type:"light", fibra:0, zuccheri:2.7, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Lambrusco (150ml)", kcal:90, p:0.1, c:5, f:0, type:"light", fibra:0, zuccheri:4.5, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Spritz (200ml)", kcal:120, p:0, c:8, f:0, type:"light", fibra:0, zuccheri:7.2, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Latte di avena (200ml)", kcal:90, p:2, c:16, f:2, type:"carb", fibra:0, zuccheri:14.4, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Latte di soia (200ml)", kcal:80, p:6, c:7, f:3, type:"protein", fibra:0, zuccheri:6.3, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"medio", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Latte di mandorla (200ml)", kcal:50, p:1, c:7, f:2, type:"light", fibra:0, zuccheri:6.3, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Protein shake (300ml)", kcal:180, p:30, c:8, f:3, type:"protein", fibra:0, zuccheri:7.2, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"alto", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Chinotto (330ml)", kcal:120, p:0, c:30, f:0, type:"carb", fibra:0, zuccheri:27, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Tè freddo limone (330ml)", kcal:110, p:0, c:27, f:0, type:"carb", fibra:0, zuccheri:24.3, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Kombucha (250ml)", kcal:55, p:0, c:14, f:0, type:"light", fibra:0, zuccheri:12.6, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Acqua di cocco (250ml)", kcal:60, p:1, c:14, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Tè verde (250ml)", kcal:2, p:0, c:0.5, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Camomilla (250ml)", kcal:1, p:0, c:0.2, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Succo di mirtillo (200ml)", kcal:110, p:0.5, c:26, f:0, type:"carb", fibra:0.5, zuccheri:23.4, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
    { name:"Tisana ai frutti di bosco (250ml)", kcal:1, p:0, c:0.2, f:0, type:"light", fibra:0, zuccheri:0, sale:0, gruppo:"Bevande", vegetariano:true, vegano:true, sazieta:"basso", pasti:["Colazione","Pranzo","Cena","Spuntino"] },
  ],
};

export const ALL_FOODS = Object.entries(FOOD_DB).flatMap(([cat,items]) =>
  items.map(f => ({ ...f, _cat: cat }))
);
